name: fullstack-challenge
services:
    app:
        build:
            context: ./docker
        ports:
            - '81:80'
        volumes:
            - '.:/var/www/html'
    mysql:
        image: 'mysql:8'
        ports:
            - '3307:3306'
        volumes:
            - 'mysql_data:/var/lib/mysql'
            - './docker:/docker-entrypoint-initdb.d'
        environment:
            MYSQL_ROOT_PASSWORD: root
    redis:
        image: 'redis:7'
        ports:
            - '6379:6379'
        volumes:
            - 'redis_data:/data'
volumes:
    mysql_data: null
    redis_data: null
    sail-mysql:
        driver: local
